### ISSUE TITLE
Let's add some automated deployment (infrastructure as a code) ?

### ISSUE THREAD

**Issue by claudio-viola** [FredericHeem/starhackit#1]
I found this little guide using Chef http://blog.carbonfive.com/2011/09/27/automating-node-js-deployment-to-ec2-with-chef/

Or ansible http://blog.carbonfive.com/2014/06/02/node-js-in-production/

**Comment by FredericHeem** [comment]
Ansible is used to deploy the stack, see https://github.com/FredericHeem/starhackit/blob/master/deploy/ansible/README.md
