### ISSUE TITLE
Can't run the backend

### ISSUE THREAD

**Issue by feesjah** [FredericHeem/starhackit#11]
Hi, first of all, thanks for this boilerplate, it's really interesting.

I cloned the repository, followed the steps, however, when running npm start i get this:

App ending with error:  { [Error: connect ECONNREFUSED 127.0.0.1:5672]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5672 }

most of the tests seem to fail aswell, am I missing some configuration I need to change to get it working ? or is something in my environment set up the wrong way ? (I m running linux mint).

Sorry if it's a stupid question, I'm quite new to all this.

Thanks in advance,

Rob

**Comment by FredericHeem** [comment]
The doc has to be improved for sure. So rabbitmq has to be installed, that's the cause of the issue.

**Comment by FredericHeem** [comment]
More documentation that describes the use of docker to install the various services: https://github.com/FredericHeem/starhackit#docker-containers

**Comment by mstroeck** [comment]
Hi @FredericHeem,

starhackit seems awesome - thanks for making it! I have the same issue installing, although I think I have set up RabbitMQ correctly. Here is the outpot of docker ps

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                   NAMES
c26b9f6b6e6a        rabbitmq:latest     "/docker-entrypoint.s"   20 minutes ago      Up 12 minutes       4369/tcp, 5671/tcp, 25672/tcp, 0.0.0.0:5672->5672/tcp   devlab_rabbitmq_mstroeck_1451822547955
```

Any ideas what might be going on?

**Comment by ro31337** [comment]
Same issue here

**Comment by FredericHeem** [comment]
How rabbitmq is configured ? Please check `server/config/default.json` 

On a mac with rabbitmq running under docker:
```
  "rabbitmq":{
    "url":"amqp://192.168.99.100"
  },
```

On linux:
```
  "rabbitmq": {
    "url":"amqp://localhost"
  },
```
