### ISSUE TITLE
node-pre-gyp ERR! on windows

### ISSUE THREAD

**Issue by fodurrr** [FredericHeem/starhackit#114]
Hi,
I have errors during npm install. I tried everything npm cache clean, install node-pre-gyp globally, but no succes.

It seems after some googling that compression-webpack-plugin is not installing correctly --> 
see this in the error messages **node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.g**

Can you help me?

here is what i get in my powershell:

PS F:\Dev\Learning\Practice\zzz Playground\starhackit-master> npm cache clean
PS F:\Dev\Learning\Practice\zzz Playground\starhackit-master> npm install

> starhackit@2.1.0 install F:\Dev\Learning\Practice\zzz Playground\starhackit-master
> (cd client && npm install) && (cd server && npm install)

> node-zopfli@1.4.0 install F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.g
z
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.2.2 (node-v48 ABI) (falling back to sour
ce compile with node-gyp)

F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli>if not defined npm_config_node
_gyp (node "C:\Dev\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else
(node "" clean )

F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli>if not defined npm_config_node
_gyp (node "C:\Dev\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fa
llback-to-build "--module=F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\
binding\node-v48-win32-x64\zopfli.node" --module_name=zopfli "--module_path=F:\Dev\Learning\Practice\zzz Playground\star
hackit-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64" )  else (node "" configure --fallback-to-b
uild "--module=F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\binding\nod
e-v48-win32-x64\zopfli.node" --module_name=zopfli "--module_path=F:\Dev\Learning\Practice\zzz Playground\starhackit-mast
er\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64" )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Dev\NodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Dev\NodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Dev\\NodeJS\\node.exe" "C:\\Dev\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.
js" "configure" "--fallback-to-build" "--module=F:\\Dev\\Learning\\Practice\\zzz Playground\\starhackit-master\\client\\
node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=F:\\Dev\
\Learning\\Practice\\zzz Playground\\starhackit-master\\client\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-
x64"
gyp ERR! cwd F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=F:\Dev\Learning\Pr
actice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --mod
ule_name=zopfli --module_path=F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\
lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\Dev\Learning\Practice\zzz Playground\starhackit-master\clien
t\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Dev\\NodeJS\\node.exe" "F:\\Dev\\Learning\\Practice\\zzz Playground\\starhackit-master\\c
lient\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli
node-pre-gyp ERR! node -v v6.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=F:\Dev\Learning\Practice\zzz Playground\starhacki
t-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=F
:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64'
 (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN react-addons-create-fragment@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-pure-render-mixin@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-transition-group@15.2.0 requires a peer of react@^15.2.0 but none was installed.
The system cannot find the path specified.

npm WARN starhackit@2.1.0 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Dev\\NodeJS\\node.exe" "C:\\Dev\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! starhackit@2.1.0 install: `(cd client && npm install) && (cd server && npm install)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the starhackit@2.1.0 install script '(cd client && npm install) && (cd server && npm install)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the starhackit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (cd client && npm install) && (cd server && npm install)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs starhackit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls starhackit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Dev\Learning\Practice\zzz Playground\starhackit-master\npm-debug.log
PS F:\Dev\Learning\Practice\zzz Playground\starhackit-master>

[npm-debug.log.txt](https://github.com/FredericHeem/starhackit/files/344526/npm-debug.log.txt)

**Comment by FredericHeem** [comment]
The log mentions that python is not found. Version 2.7 is required on windows

**Comment by FredericHeem** [comment]
You could also try to install the dependencies without the optional one:
npm i --no-optional
Not sure if it works but it's worth trying.

**Comment by fodurrr** [comment]
Same issue when Python 2.7 is installed and running from command prompt without issues.

I found on Github that some other project has the same issues, but I do not know the solution....:(

same with npm i --no-optional :(
[npm-debug.txt](https://github.com/FredericHeem/starhackit/files/344552/npm-debug.txt)



PS F:\Dev\Learning\Practice\zzz Playground\starhackit-master> python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
PS F:\Dev\Learning\Practice\zzz Playground\starhackit-master> npm install

> starhackit@2.1.0 install F:\Dev\Learning\Practice\zzz Playground\starhackit-master
> (cd client && npm install) && (cd server && npm install)


> node-zopfli@1.4.0 install F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.g
z
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.2.2 (node-v48 ABI) (falling back to sour
ce compile with node-gyp)

F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli>if not defined npm_config_node
_gyp (node "C:\Dev\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else
(node "" clean )

F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli>if not defined npm_config_node
_gyp (node "C:\Dev\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fa
llback-to-build "--module=F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\
binding\node-v48-win32-x64\zopfli.node" --module_name=zopfli "--module_path=F:\Dev\Learning\Practice\zzz Playground\star
hackit-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64" --python=python2.7 --msvs_version=2015 )
else (node "" configure --fallback-to-build "--module=F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\n
ode_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node" --module_name=zopfli "--module_path=F:\Dev\Learning\
Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64" --python=pytho
n2.7 --msvs_version=2015 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Dev\NodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Dev\NodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Dev\\NodeJS\\node.exe" "C:\\Dev\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.
js" "configure" "--fallback-to-build" "--module=F:\\Dev\\Learning\\Practice\\zzz Playground\\starhackit-master\\client\\
node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=F:\\Dev\
\Learning\\Practice\\zzz Playground\\starhackit-master\\client\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-
x64" "--python=python2.7" "--msvs_version=2015"
gyp ERR! cwd F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=F:\Dev\Learning\Pr
actice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --mod
ule_name=zopfli --module_path=F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\
lib\binding\node-v48-win32-x64 --python=python2.7 --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\Dev\Learning\Practice\zzz Playground\starhackit-master\clien
t\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Dev\\NodeJS\\node.exe" "F:\\Dev\\Learning\\Practice\\zzz Playground\\starhackit-master\\c
lient\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli
node-pre-gyp ERR! node -v v6.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=F:\Dev\Learning\Practice\zzz Playground\starhacki
t-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=F
:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64
--python=python2.7 --msvs_version=2015' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN react-addons-create-fragment@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-pure-render-mixin@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-transition-group@15.2.0 requires a peer of react@^15.2.0 but none was installed.
The system cannot find the path specified.

npm WARN starhackit@2.1.0 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Dev\\NodeJS\\node.exe" "C:\\Dev\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! starhackit@2.1.0 install: `(cd client && npm install) && (cd server && npm install)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the starhackit@2.1.0 install script '(cd client && npm install) && (cd server && npm install)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the starhackit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (cd client && npm install) && (cd server && npm install)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs starhackit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls starhackit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Dev\Learning\Practice\zzz Playground\starhackit-master\npm-debug.log
PS F:\Dev\Learning\Practice\zzz Playground\starhackit-master> npm i --no-optional

> starhackit@2.1.0 install F:\Dev\Learning\Practice\zzz Playground\starhackit-master
> (cd client && npm install) && (cd server && npm install)


> node-zopfli@1.4.0 install F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.g
z
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.2.2 (node-v48 ABI) (falling back to sour
ce compile with node-gyp)

F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli>if not defined npm_config_node
_gyp (node "C:\Dev\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else
(node "" clean )

F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli>if not defined npm_config_node
_gyp (node "C:\Dev\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fa
llback-to-build "--module=F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\
binding\node-v48-win32-x64\zopfli.node" --module_name=zopfli "--module_path=F:\Dev\Learning\Practice\zzz Playground\star
hackit-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64" --python=python2.7 --msvs_version=2015 )
else (node "" configure --fallback-to-build "--module=F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\n
ode_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node" --module_name=zopfli "--module_path=F:\Dev\Learning\
Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64" --python=pytho
n2.7 --msvs_version=2015 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Dev\NodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Dev\NodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Dev\\NodeJS\\node.exe" "C:\\Dev\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.
js" "configure" "--fallback-to-build" "--module=F:\\Dev\\Learning\\Practice\\zzz Playground\\starhackit-master\\client\\
node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=F:\\Dev\
\Learning\\Practice\\zzz Playground\\starhackit-master\\client\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-
x64" "--python=python2.7" "--msvs_version=2015"
gyp ERR! cwd F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=F:\Dev\Learning\Pr
actice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --mod
ule_name=zopfli --module_path=F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\
lib\binding\node-v48-win32-x64 --python=python2.7 --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\Dev\Learning\Practice\zzz Playground\starhackit-master\clien
t\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Dev\\NodeJS\\node.exe" "F:\\Dev\\Learning\\Practice\\zzz Playground\\starhackit-master\\c
lient\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd F:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli
node-pre-gyp ERR! node -v v6.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=F:\Dev\Learning\Practice\zzz Playground\starhacki
t-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=F
:\Dev\Learning\Practice\zzz Playground\starhackit-master\client\node_modules\node-zopfli\lib\binding\node-v48-win32-x64
--python=python2.7 --msvs_version=2015' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN react-addons-create-fragment@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-pure-render-mixin@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-transition-group@15.2.0 requires a peer of react@^15.2.0 but none was installed.
The system cannot find the path specified.

npm WARN starhackit@2.1.0 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Dev\\NodeJS\\node.exe" "C:\\Dev\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "i" "--no-optional"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! starhackit@2.1.0 install: `(cd client && npm install) && (cd server && npm install)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the starhackit@2.1.0 install script '(cd client && npm install) && (cd server && npm install)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the starhackit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (cd client && npm install) && (cd server && npm install)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs starhackit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls starhackit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Dev\Learning\Practice\zzz Playground\starhackit-master\npm-debug.log
PS F:\Dev\Learning\Practice\zzz Playground\starhackit-master> npm i --no-optional

**Comment by fodurrr** [comment]
same issue with an other project on windows
[https://github.com/AngularClass/angular2-webpack-starter/issues/652](url)

**Comment by fodurrr** [comment]
when I try  npm install node-zopfli in the client folder I have the same errors, it seems acces is denied  for node-zopfli download from amazon server???

**Comment by FredericHeem** [comment]
I had the same issue while installing behind a corporate firewall and use the --no-optional option

**Comment by fodurrr** [comment]
Now I tried through my VPN provider, no help :( I will try at home tomorrow :)

**Comment by anankitpatil** [comment]
Got this on OSX El Capitan. Tried installing npm node-gyp -g to no avail. 

Any solutions?



> libpq@1.8.3 install /Users/AP/Documents/VirtualServer/starhack/server/node_modules/libpq
> node-gyp rebuild

/bin/sh: pg_config: command not found
gyp: Call to 'pg_config --libdir' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/AP/Documents/VirtualServer/starhack/server/node_modules/libpq
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
starhackit-api@0.0.1 /Users/AP/Documents/VirtualServer/starhack/server
└── (empty)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! libpq@1.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.8.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libpq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/AP/Documents/VirtualServer/starhack/server/npm-debug.log
npm ERR! code 1

npm WARN starhackit@2.1.0 No license field.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! starhackit@2.1.0 install: `(cd client && npm install) && (cd server && npm install)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the starhackit@2.1.0 install script '(cd client && npm install) && (cd server && npm install)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the starhackit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (cd client && npm install) && (cd server && npm install)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs starhackit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls starhackit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/AP/Documents/VirtualServer/starhack/npm-debug.log

**Comment by FredericHeem** [comment]
Could you try to install postgres with brew?

**Comment by FredericHeem** [comment]
https://github.com/FredericHeem/starhackit/pull/123
