### ISSUE TITLE
Saving profile: Name Validation Error

### ISSUE THREAD

**Issue by geirman** [FredericHeem/starhackit#12]
I'm not clear what the benefit of creating a profile is since I'm only given a logout or profile option in the nav menu, but regardless... I'm unable to create a profile because my name never validates

<img width="435" alt="2015-10-30_0846" src="https://cloud.githubusercontent.com/assets/1640318/10850469/15f0c68a-7ee3-11e5-8bde-020a1d5312e6.png">

**Comment by FredericHeem** [comment]
Saving the profile is still a work in progress. I'll tried to implement it soon.

**Comment by geirman** [comment]
what benefit is there having a profile?

**Comment by FredericHeem** [comment]
Most of the web apps have a profile page, feel free to remove it in your app. This page also serves as an example on how to write a react based frontend.
Saving the profile is now partially implemented in the master branch.

**Comment by FredericHeem** [comment]
Changing the username is working right now.
