### ISSUE TITLE
refresh when logged in returns back to main Landing page

### ISSUE THREAD

**Issue by itsjimbo** [FredericHeem/starhackit#120]
Just wondering the most effective way to handle a refresh (but the user is still logged in), and you don't want them to be directed to the main page, rather a logged in main page...
I'm not too sure if this would be a good fix

https://github.com/FredericHeem/starhackit/blob/master/client/src/app/routes.js#L9-L15

```
  indexRoute: {
                    getComponent: (nextState, cb) => {
                        return require.ensure([], (require) => {
                            // cb(null, require('parts/core/views/mainLanding').default)
                            (store && store.getState() && store.getState().auth.auth.authenticated)?
                                cb(null, require('parts/core/views/authLanding').default):
                                cb(null, require('parts/core/views/mainLanding').default);
                        })
                    }
                },

```

**Comment by FredericHeem** [comment]
Try modifying this line: https://github.com/FredericHeem/starhackit/blob/master/client/src/app/parts/auth/views/loginView.js#L23

**Comment by itsjimbo** [comment]
Thanks for the tip...I figured it out, just sharing what I did in case  others wanted to know..
I just modified navbar, because that receives the authentication status after the main page has loaded.



https://github.com/FredericHeem/starhackit/blob/master/client/src/app/parts/core/components/navbar.js#L48-L49
```
    componentWillMount () {
        /**
         * If the user comes back to the main site (eg a refresh on '/') ensure they get re-directed to some authenticated view, here I am choosing /app/profile
         */
        if (this.props.route.path==='/' && this.props.authenticated)
        {
            this.context.router.push(`/app/profile`);
        }
    },
```


Also pass props to navbar so it knows our current route info

https://github.com/FredericHeem/starhackit/blob/master/client/src/app/parts/auth/views/applicationView.js#L22
```
<NavBar authenticated={authenticated} {...props} />
```

**Comment by FredericHeem** [comment]
Can I close the issue ?

**Comment by itsjimbo** [comment]
sure you can close it, thanks for all the help!
