### ISSUE TITLE
Syntax grammar style 

### ISSUE THREAD

**Issue by itsjimbo** [FredericHeem/starhackit#121]
Just curious if there any particular reason that the entire application is written with 
```
export default React.createClass( {
```
instead of 
```
export default class Foo extends React.Component {
```
Not an issue, just wanted to understand rationale...

**Comment by FredericHeem** [comment]
Please have a look at my comments on why I prefer `createClass` over `class`: https://github.com/reactjs/core-notes/pull/15#issuecomment-220800536
Ultimately, favor stateless component over stateful component.

**Comment by itsjimbo** [comment]
Just following up, interestingly FB seems determined to deprecate React.createClass, or move it to a separate package, what does this spell out for StarHackIt or any thoughts?

I followed up on some of their notes, and they were running 80% coverage on class usage using their ES2015 converter..
https://github.com/reactjs/core-notes/blob/master/2016-07/july-28.md
