### ISSUE TITLE
Error during install. Node 6.x not supported?

### ISSUE THREAD

**Issue by coooolers** [FredericHeem/starhackit#122]
I have node 6.2.2 installed but seems like some modules do not support 6.x version. The following error is there during the npm install

node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.2.2 (node-v48 ABI) (falling back to source compile with node-gyp)

If I am correct what version of node does it support?

Can anybody pl. answer the following:

1. Do I need to do npm install in both the server and client directories separately?

2. What are the prerequisites before I run this package? Do I need to install the Rabbit MQ and sqllite db both? Or can I use PostgreSQL directly without installing SQL Lite and removing the sqlite module dependency from the package.json?

3. Can I use Gmail SMTP Server for sending email for testing purposes? Or does it support Mailgun only?

**Comment by FredericHeem** [comment]
Please see the updated [backend README](https://github.com/FredericHeem/starhackit/tree/master/server)
