### ISSUE TITLE
Error on install node-gyp rebuild and libpq on OS X

### ISSUE THREAD

**Issue by danhakin** [FredericHeem/starhackit#128]
Once I do a git clone and npm install I get the following error: 

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/dus/.nvm/versions/node/v6.3.1/bin/node" "/Users/dus/.nvm/versions/node/v6.3.1/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! libpq@1.8.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libpq@1.8.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libpq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.

**Comment by FredericHeem** [comment]
I'll investigate, in the meantime, please remove the Postgres dependencies in `server/package.json` and use SQLite instead: 
```
    "pg": "6.0.3",
    "pg-hstore": "2.3.2",
    "pg-native": "1.10.0",
```

**Comment by FredericHeem** [comment]
Could you try to remove the `server/node_modules` and re-run `npm install` ?

**Comment by danhakin** [comment]
I installed postgres via homebrew and retried "npm install" and it works now. 

The weird thing is that I tried removing postgres dependencies in package.json and removing srv/node_modules as you mentioned and I kept getting the same error is like there is some other dependency to libpq besides the three pg* modules.

Thanks for your help and hard work, it is an awesome project!

**Comment by FredericHeem** [comment]
Now, both the frontend and the backend no longer rely on a C++ compiler, that should make the first install much easier.
