### ISSUE TITLE
Session Timeout feature

### ISSUE THREAD

**Issue by ramandhingra** [FredericHeem/starhackit#147]
When the end user is idle for a certain period of time, let's say, 10 minutes and when he interacts with the system after 10 minutes, he should be redirected to Login page.

**Comment by FredericHeem** [comment]
The json web token expiry can be set in https://github.com/FredericHeem/starhackit/blob/133ddff1c27a92b853490e129a2341e6e2b96b96/server/src/plugins/users/authentication/AuthenticationRouter.js#L20

**Comment by ramandhingra** [comment]
How is the web token expiry related to session timeout? I didn't get it.

**Comment by FredericHeem** [comment]
See https://github.com/FredericHeem/starhackit/pull/181/files
