### ISSUE TITLE
Authentication Api missing features marked as TODOs

### ISSUE THREAD

**Issue by ramandhingra** [FredericHeem/starhackit#148]
Can I request that these features be implemented soon?

a. verifyEmailCode function
//TODO Transaction
//Token should expire after a certain period

b. verifyResetPasswordToken
// Has the token expired ?
//TODO delete token

I think they should be at a priority.

Thanks in advance

**Comment by FredericHeem** [comment]
See https://github.com/FredericHeem/starhackit/pull/178
