### ISSUE TITLE
Move to Redux

### ISSUE THREAD

**Issue by claudio-viola** [FredericHeem/starhackit#17]
Redux makes you implement faster and better.
Let's move to Redux? 
http://rackt.org/redux/docs/basics/UsageWithReact.html

**Comment by FredericHeem** [comment]
What are the benefits of using redux over reflux ?

**Comment by FredericHeem** [comment]
For now, let's stick to reflux which is fine, a lot more expressive and less boilerplate than the other flux implementations.
Feel free to create another frontend based on redux or on any other flux libraries.
