### ISSUE TITLE
Implement real RESTFul api

### ISSUE THREAD

**Issue by claudio-viola** [FredericHeem/starhackit#19]
Decorate controller response following HATEAOS standards.
At least:
 Links { self,next,prev,last,first, relations links .} 
meta: (method, total count, filters)  
data: {
relations
}

**Comment by FredericHeem** [comment]
Let's design the API according to an aspiring REST API standard: [RAPIS](https://github.com/lambda2/rapis)

**Comment by FredericHeem** [comment]
See https://github.com/FredericHeem/starhackit/pull/102
