### ISSUE TITLE
Having problems installing from Yeoman

### ISSUE THREAD

**Issue by scott-greenough** [FredericHeem/starhackit#194]
The errors I'm getting are in the log file below at the bottom. I had to change the extension to .txt because it wouldn't allow .log.

[npm-debug.txt](https://github.com/FredericHeem/starhackit/files/458067/npm-debug.txt)

Is there some kind of permission issue or something like that?

Scott

**Comment by FredericHeem** [comment]
Can you try to clone the project from GitHub instead ?

**Comment by scott-greenough** [comment]
I cloned it and then ran npm install

Things seemed to work fine at that point. I'll play around some more when I
get a moment and see where I'm at.

Scott

**Comment by Sabst** [comment]
@FredericHeem 
`npm install` looks fine with me too.
Now `npm start` fails for some reason and I have no time to investigate right now... I think this is the main issue:
```
api-0 Executing (default): INSERT INTO `groups` (`id`,`name`,`description`) VALUES (NULL,'Admin','Administrator, can perform any actions'),(NULL,'AdminReadOnly','A Administrator group with read only access'),(NULL,'User','An authenticated user');
api-0 App ending with error:  { [SequelizeUniqueConstraintError: Validation error]
api-0   name: 'SequelizeUniqueConstraintError',
api-0   message: 'Validation error',
api-0   errors: 
api-0    [ { message: 'name must be unique',
api-0        type: 'unique violation',
api-0        path: 'name',
api-0        value: null } ],
api-0   fields: [ 'name' ] }
api-0 App ending with error:  {"name":"SequelizeUniqueConstraintError","message":"Validation error","errors":[{"message":"name must be unique","type":"unique violation","path":"name","value":null}],"fields":["name"]}
2016-09-21 22:37:48: App [api] with id [0] and pid [26214], exited with code [0] via signal [SIGINT]
```
I did not configure anything so far and did not start any docker image (from the doc, I don't think this is required for such a basic use).

What is the trick?

**Comment by FredericHeem** [comment]
Can you delete db.dev.sqlite and rerun npm start?

**Comment by Sabst** [comment]
Yes, I tried that already without success.
Here is another one I missed previously and that might explain why bootstrap is replayed:
```
name: 'SequelizeTimeoutError',
api-0   message: 'SQLITE_BUSY: database is locked',
api-0   parent: 
api-0    { [Error: SQLITE_BUSY: database is locked]
api-0      errno: 5,
api-0      code: 'SQLITE_BUSY',
api-0      sql: 'DELETE FROM `user_pendings` WHERE `email` = \'admin@myapp.com\'' },
api-0   original: 
api-0    { [Error: SQLITE_BUSY: database is locked]
api-0      errno: 5,
api-0      code: 'SQLITE_BUSY',
api-0      sql: 'DELETE FROM `user_pendings` WHERE `email` = \'admin@myapp.com\'' },
api-0   sql: 'DELETE FROM `user_pendings` WHERE `email` = \'admin@myapp.com\'' }
api-0 App ending with error:  {"name":"SequelizeTimeoutError","message":"SQLITE_BUSY: database is locked","parent":{"errno":5,"code":"SQLITE_BUSY","sql":"DELETE FROM `user_pendings` WHERE `email` = 'admin@myapp.com'"},"original":{"errno":5,"code":"SQLITE_BUSY","sql":"DELETE FROM `user_pendings` WHERE `email` = 'admin@myapp.com'"},"sql":"DELETE FROM `user_pendings` WHERE `email` = 'admin@myapp.com'"}
2016-09-22 06:43:52: App [api] with id [0] and pid [4784], exited with code [0] via signal [SIGINT]
```
I don't see  who else could lock this file, I think it's the server itself.
During the server startup, `lsof` gives this kind of output:
```
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF      NODE NAME
node    14516    z   11ur  REG  252,0    22528 111456837 db.dev.sqlite
node    14516    z   12ur  REG  252,0    22528 111456837 db.dev.sqlite
```
I think I just heard your new question :-)
```
npm -v
3.7.1
node -v
v5.12.0
```
Is that an issue? (that was required by another JS environment but I can change if needed)

**Comment by FredericHeem** [comment]
For now, please use PostgreSQL while I dig into the issue related to sqlite

**Comment by FredericHeem** [comment]
See https://github.com/FredericHeem/starhackit/issues/195 for details

**Comment by Sabst** [comment]
Switching to PostgreSQL makes a big difference, thanks.
I could run most of the client features after enabling the e-mail too (would be nice to have a log with the verification link to avoid - for a quick test - the e-mail setup).
The only remaining issue is a 401 error when I click on the admin menu. Will look into this authorization issue later.

**Comment by Sabst** [comment]
BTW, thanks for fixing the sqlite version. This is working fine now.
