### ISSUE TITLE
Missing client-side testing

### ISSUE THREAD

**Issue by claudio-viola** [FredericHeem/starhackit#2]
We are missing testing on the client-side. React testing etc.

**Comment by thecodingwhale** [comment]
yeah that would be great! any suggestions to implement this?

**Comment by claudio-viola** [comment]
@thecodingwhale https://discuss.reactjs.org/t/whats-the-prefered-way-to-test-react-js-components/26/20      
http://reactkungfu.com/2015/07/approaches-to-testing-react-components-an-overview/
Seems like it's between: ShallowRendering or mocha/jsdom while ShallowRendering has some limitations

Jsdom Example https://github.com/robertknight/react-testing

Do you want do it?

**Comment by thecodingwhale** [comment]
ohh what a great link thanks for sharing! btw I'm still learning the proper way :)

**Comment by FredericHeem** [comment]
Let's have a look also at `protractor`: 
* https://github.com/angular/protractor
* http://www.joelotter.com/2015/04/18/protractor-reactjs.html

and `nightwatchjs`: http://nightwatchjs.org/

**Comment by FredericHeem** [comment]
`npm test` now invokes *nightwatch*. The *postinstall* npm script also installs the *selenium* jar. A few test cases are provided. Adding a new one is relatively easy. Contribution welcomed.
