### ISSUE TITLE
JWT: json web token

### ISSUE THREAD

**Issue by FredericHeem** [FredericHeem/starhackit#21]
Implement authentication using JWT over cookies:
* https://github.com/auth0/node-jsonwebtoken
* https://github.com/stiang/koa-jwt
* https://github.com/themikenicholson/passport-jwt
* https://github.com/mzabriskie/axios : for the frontend, to intercept and add the right http header

**Comment by claudio-viola** [comment]
Agreed. Up. that's the way to go http://jwt.io/

**Comment by FredericHeem** [comment]
This blog post has a nice way to integrate JWT with React and Axios: http://adamalbrecht.com/2015/07/20/authentication-using-json-web-tokens-using-rails-and-react/

**Comment by FredericHeem** [comment]
implemented in 2.0.0
