### ISSUE TITLE
api server 503 error 

### ISSUE THREAD

**Issue by OndroS** [FredericHeem/starhackit#210]
Hi! I'm complete noob in this sector and I'll be glad if you help me with it. I'm missing some detailed documentations about some info about api and db. When I'm trying to register, server give me 503 error - {code: 503, name: "MessageQueueNotAvailable", message: "Message queue channel not available"}. Can somebody tell me how to properly configurate it please? Thanks for all reactions.

**Comment by FredericHeem** [comment]
Please a look at https://github.com/FredericHeem/starhackit/tree/master/server#for-development
and tell me if it's working.
