### ISSUE TITLE
monitoring

### ISSUE THREAD

**Issue by claudio-viola** [FredericHeem/starhackit#3]

**Comment by FredericHeem** [comment]
Now that redux is used as the state management, a specific redux middleware can be implemented to report all the actions.

**Comment by FredericHeem** [comment]
Let's explore the various solution for monitoring:
* relic
* google analytics
* other ?

**Comment by FredericHeem** [comment]
Analytics with redux is really easy and requires to implement a `middleware`: see a concrete implementation for google analytics: https://github.com/FredericHeem/starhackit/blob/master/client/src/app/parts/analytics/AnalyticsModule.js
