### ISSUE TITLE
SequelizeDatabaseError: column Groups.Permissions.get does not exist

### ISSUE THREAD

**Issue by sslash** [FredericHeem/starhackit#31]
I am getting this error when I run the code locally. I haven't changed anything except setting the database to be postgres. I have also run the migrations. In my database I have the GET column, but it is in uppercase letters.

**Comment by sslash** [comment]
In my database I have the GET column, but it is in uppercase letters.

**Comment by FredericHeem** [comment]
Can you try to drop the database and restart the app without running the migrations? Sequelize will automatically provision the database when empty.
FYI, GET is in uppercase due to an issue with Sequelize that doesn't allow columns to be named `get`.

**Comment by sslash** [comment]
Nopes. Just to be sure I created a brand new database. Got the same error. I am running node 4.2, postgres 9.4 and mac osx (not with docker)

**Comment by FredericHeem** [comment]
You're using the latest code, aren't you? I remember fixing this bug a while ago.

**Comment by sslash** [comment]
Yes that must have been the issue. I used the yeoman generator a couple of days ago. But I see now that the code that is generated is older then the newest on github. Cloned the repo instead, and now it works. Thanks!

**Comment by FredericHeem** [comment]
Created this issue instead: https://github.com/FredericHeem/starhackit/issues/32
