### ISSUE TITLE
Error installing postgres

### ISSUE THREAD

**Issue by mredaelli** [FredericHeem/starhackit#314]
When running `yarn run setup`, I get

````
Digest: sha256:0adc410aa5e45b817bc8f29d5845c4941ad03b63e9584bc7f8654562e60424cf
Status: Downloaded newer image for node:8
docker: Error response from daemon: Could not get container for bc_postgres_BkWrewrFZ.
See 'docker run --help'.
````

**Comment by FredericHeem** [comment]
Which OS are you working on ? The `setup` npm task is optional anyway.

**Comment by mredaelli** [comment]
That was fast :)
Debian testing, kernel 4.9.30-2+deb9u3

**Comment by FredericHeem** [comment]
the `setup` task is just a wrapper for `binci` which installs and run docker containers. 
On Linux, it's much easier to install postgres with apt.
