### ISSUE TITLE
how to debug server side code?

### ISSUE THREAD

**Issue by kiinoo** [FredericHeem/starhackit#395]
npm run start will start the server. I've seen it will build src into 'build' folder, and start a pm2 to monitor the node process starts from build/index.js.

but how to debug? if I set the debug entry as "build/index.js" it will debug the compiled code, not the source file in "src" folder.

anyone knows how to debug "src" files? or any clues that I can refer to?

thanks very much.

**Comment by FredericHeem** [comment]
Better late than never: https://fredericheem.gitbook.io/starhackit/backend/debugging
