### ISSUE TITLE
After admin npm start - page not found

### ISSUE THREAD

**Issue by bigbadbrad** [FredericHeem/starhackit#547]
Hi,
Thanks for providing this starter kit - great for new coders like myself.  When I open as admin:
$ npm start -- --open-page=admin

the page goes here: http://0.0.0.0:8080/admin
and says 'Page Not Found 404'

I found that I can correct the problem if I go here:
http://0.0.0.0:8080/admin/auth/login?nextPath=/admin/users

Then I'm able to login as admin, and I get correctly redirected to:
http://0.0.0.0:8080/admin/users

How do I npm start as admin and go directly to the login page?

**Comment by FredericHeem** [comment]
2 new npm scripts have been added:
```
npm run start:admin
```
and 
```
npm run start:user
```

Thanks for the report.
