### ISSUE TITLE
lots of lint warnings at client npm start (mostly: "Use L10ns not a string literal")

### ISSUE THREAD

**Issue by rkoberg** [FredericHeem/starhackit#55]
/Users/rkoberg/Sites/fwi-app/client/src/app/components/alert.js
  19:22  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  21:22  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/components/restTableComponent.js
   47:22  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
   48:22  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
   49:22  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
   82:68  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
   98:68  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
  127:9   warning  Each then() should return a value or throw  promise/always-return

/Users/rkoberg/Sites/fwi-app/client/src/app/mixins/RestWrapper.js
  21:13  warning  Each then() should return a value or throw  promise/always-return
  60:57  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/admin/userComponent.js
  17:22  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  18:22  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  19:22  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  20:22  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/admin/usersComponent.js
  47:46  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/auth/authModule.js
  135:26  warning  'store' is defined but never used  no-unused-vars

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/auth/components/localLoginForm.js
  15:29  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  15:46  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  15:59  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  15:76  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/auth/components/localSignupForm.js
  28:22  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  30:22  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/auth/views/applicationView.js
  23:41  warning  '__VERSION__' is not defined  no-undef

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/auth/views/forgotView.js
  12:5   warning  'debug' is defined but never used           no-unused-vars
  46:21  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
  47:28  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
  49:20  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
  71:21  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
  72:28  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
  74:20  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
  76:20  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
  94:9   warning  Each then() should return a value or throw  promise/always-return

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/auth/views/logoutView.js
  17:25  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/auth/views/registerView.js
  26:72  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  34:21  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  36:21  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/auth/views/registrationCompleteView.js
  40:25  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  53:79  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  60:78  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/auth/views/resetPasswordView.js
  33:25  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  44:78  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  57:28  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  81:28  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/core/components/footer.js
  20:34   warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  21:34   warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  22:125  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/core/views/mainLanding.js
   68:33  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
   69:33  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
   70:33  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
   87:37  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  117:37  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  148:37  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  188:37  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals
  257:37  warning  Use L10ns not a string literal  jsx-extras/jsx-no-string-literals

/Users/rkoberg/Sites/fwi-app/client/src/app/parts/profile/components/profileForm.js
   54:21  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
   88:33  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
  107:56  warning  Use L10ns not a string literal              jsx-extras/jsx-no-string-literals
  130:9   warning  Expected catch() or return                  promise/catch-or-return
  130:9   warning  Each then() should return a value or throw  promise/always-return

✖ 59 problems (0 errors, 59 warnings)

**Comment by FredericHeem** [comment]
Most of the warning has been fixed, the remaining one could be considered false positive.

**Comment by FredericHeem** [comment]
All warning has been removed, new warnings will be directly displayed to the browser thank to `webpack-hud`.
