### ISSUE TITLE
adding icons to mdlean buttons

### ISSUE THREAD

**Issue by bigbadbrad** [FredericHeem/starhackit#558]
This isn't a bug, but how can icons be added to menuItems.ts to display in navbar?

When I add icons to the menuItems, I get the error:
Error: Objects are not valid as a React child (found: object with keys {FaUser}). If you meant to render a collection of children, use an array instead.

<img width="785" alt="icon_in_menuItems" src="https://user-images.githubusercontent.com/1226677/90948115-1740cb80-e3f0-11ea-9299-338a4d0d80bf.png">
<img width="679" alt="icon_added_to_button" src="https://user-images.githubusercontent.com/1226677/90948120-19a32580-e3f0-11ea-8375-953f9957be06.png">
<img width="1432" alt="error" src="https://user-images.githubusercontent.com/1226677/90948121-1ad45280-e3f0-11ea-9874-c1682278ec64.png">

**Comment by FredericHeem** [comment]
Use `createElement` instead of bracket, see https://github.com/FredericHeem/starhackit/pull/559

**Comment by bigbadbrad** [comment]
Perfect thx!
