### ISSUE TITLE
Cannot resolve module in npm 3

### ISSUE THREAD

**Issue by Semigradsky** [FredericHeem/starhackit#7]
![image](https://cloud.githubusercontent.com/assets/1198848/10753861/bc181270-7ca4-11e5-89e0-0d39e3d7c2ae.png)

From `client/webpack.config.js`:
```js
entry: {
  vendor: [
    ...
    'react-dropzone-component/node_modules/dropzone/dist/dropzone.css',
    ...
```

Because `npm` now installed dependecies maximally flat.

**Comment by FredericHeem** [comment]
Actually, *react-dropzone-component* was not used yet so it has now been removed.
Thanks you.
